spring:
  application:
    name: hashing-machine
  threads:
    virtual:
      enabled: true

server:
  http2:
    enabled: true
  tomcat:
    remoteip:
      remote-ip-header: "X-Forwarded-For"
      protocol-header: "X-Forwarded-Proto"
